cmake_minimum_required(VERSION 3.28)

project(nbody VERSION 0.1.0)

include(CTest)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

# STD assertions activated
if (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
  string(APPEND CMAKE_CXX_FLAGS " -D_GLIBCXX_ASSERTIONS")
elseif (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  string(APPEND CMAKE_CXX_FLAGS " -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE")
endif()

# Address sanitizer Debug mode
string(APPEND CMAKE_CXX_FLAGS_DEBUG " -fsanitize=address,undefined")
if (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
  string(APPEND CMAKE_CXX_FLAGS " -D_GLIBCXX_SANITIZE_STD_ALLOCATOR")
endif()
string(APPEND CMAKE_EXE_LINKER_FLAGS_DEBUG " -fsanitize=address,undefined")

# If used (sfml)
find_package(SFML 2.6 COMPONENTS graphics REQUIRED)

# Main executable
add_executable(nbody
    apps/main.cpp
)

target_link_libraries(nbody PRIVATE sfml-graphics)

# Tests
if (BUILD_TESTING)
    add_executable(nbody.t
        tests/main_test.cpp
    )
    # # if we use sfml
    target_link_libraries(progetto.t PRIVATE sfml-graphics sfml-window sfml-system)

    add_test(NAME nbody.t COMMAND nbody.t)


endif()